import React from "react";

function Performances() {
    return (
        <div>
            <h1>FAIRS, FESTIVALS & SPECIAL EVENTS</h1>

            <p>
                ABILENE CHILDREN’S ARTS & LITERARY FESTIVAL, ABILENE, TEXAS
                MIDLAND COUNTY FAIR, MIDLAND, TEXAS
                CENTRAL TEXAS STATE FAIR, BELTON TEXAS
                AUSTIN COUNTY FAIR, BELLVILLE, TEXAS
                DICKENS ON MAIN, BOERNE, TEXAS
                GRAND KIDS FESTIVAL, GALVESTON, TEXAS
                PASADENA LIVESTOCK SHOW AND RODEO, PASADENA, TEXAS
                WASHINGTON COUNTY FAIR, BRENHAM, TEXAS
                JACKSON COUNTY FAIR, EDNA, TEXAS
                FRISCOVANIA, FRISCO, TEXAS
                SAN JACINTO FESTIVAL (2 CONSECUTIVE YEARS), LA PORTE, TEXAS
                FORT BEND COUNTY FAIR, ROSENBERG, TEXAS
                WALLER COUNTY FAIR (BARNYARD BUDDIES 4 CONSECUTIVE YEARS), HEMPSTEAD, TEXAS
                TALL SHIPS FESTIVAL, GALVESTON, TEXAS
                WALKER COUNTY FAIR (MULTIPLE YEARS), HUNTSVILLE, TEXAS
                COLORADO COUNTY FAIR, COLUMBUS, TEXAS
                CZHILISPIEL FESTIVAL, FLATONIA, TEXAS
                TEXARKANA CAJUN CATFISH FESTIVAL, TEXARKANA, TEXAS
                SEABROOK CELEBRATION (2 CONSECUTIVE YEARS), SEABROOK, TEXAS
                CONROE CAJUN CATFISH FESTIVAL (MULTIPLE YEARS), CONROE, TEXAS
                GALVESTON COUNTY FAIR, HITCHCOCK, TEXAS
                FAYETTE COUNTY FAIR, LA GRANGE, TEXAS
                DICKENS ON THE STRAND (MULTIPLE YEARS), GALVESTON, TEXAS

                FREEDOM OVER TEXAS (3 CONSECUTIVE YEARS), HOUSTON, TEXAS
                WOODLANDS RED, WHITE AND BLUE FESTIVAL (3 CONSECUTIVE YEARS), WOODLANDS, TEXS
                AUSTON JUGGLE-FEST (FEATURED PERFORMER 3 YEARS), AUSTIN, TEXAS
                RAINFOREST CAFE (FEATURED ACT SUMMER OF 2014), GALVESTON, TEXAS
                KBR KIDS DAY ON BUFFALO BAYOU, HOUSTON, TEXAS
                HOUSTON CHILDREN’S FESTIVAL, HOUSTON, TEXAS
                GREAT AMERICAN RIB COOK-OFF (12 CONSECUTIVE YEARS), CLEVELAND, OHIO
                CLEVELAND TALL SHIPS FESTIVAL (2 CONSECUTIVE YEARS), CLEVELAND, OHIO
                CLEVELAND KIDSFEST (9 CONSECUTIVE YEARS), CLEVELAND, OHIO
                MEDINA COUNTY FAIR, MEDINA, OHIO
                MAJOR LEAGUE BASEBALL ALL STAR FANFEST, CLEVELAND, OHIO
                THE REMBRANDTS PROMOTIONAL TOUR (OPENING ACT), CLEVELAND, OHIO
                LEAN REDBONE (OPENING ACT), CLEVELAND, OHIO
                HERITAGE DAYS, (4 CONSECUTIVE YEARS), OLMSTEAD FALLS, OHIO
                NGTC/MANSFIELD RIB COOK-OFF, MANSFIELD, OHIO
                WGAR COUNTRY MUSIC FESTIVAL (3 CONSECUTIVE YEARS), CLEVELAND, OHIO
                BUGS ON BROADWAY (OPENING ACT), CLEVELAND, OHIO
                <h1>TELEVISION & FILM</h1>

                AMERICA’S GOT TALENT, NBC NATIONAL BROADCAST, 2018 SEASON, 4 EPISODES
                MORNING NEWSCAST, KHOU 11, HOUSTON, TEXAS
                FOX 8 IN THE MORNING, CLEVELAND, OHIO
                DIARY OF A HITMAN, COLUMBIA TRISTAR
                BUDWEISER CLEVELAND 500 SHOW, WEWS-TV5, CLEVELAND, OHIO</p>

        </div>
    );
}

export default Performances